### ISSUE TITLE
代码编译不起来

### ISSUE THREAD

**Issue by cavilZ** [1ibrary/1ibrary-front-end#13]
编译不起来:include BOOST_USER_CONFIG这里报错"boost/config/user.hpp"file not found

**Comment by Lxxyx** [comment]
http://reactnative.cn/docs/0.47/getting-started.html

**Comment by cavilZ** [comment]
已解决。不过停留在启动页。

**Comment by Lxxyx** [comment]
按步骤来。
启动页会久一点，是在build东西。
