### ISSUE TITLE
关于demo运行报错的问题

### ISSUE THREAD

**Issue by iOS-chenqiulin** [1ibrary/1ibrary-front-end#23]
我之前创建的项目都是0.44.3之前的项目，今天发下你的项目版本是0.47.2版本的，xcode运行就报错
'React/RCTBundleURLProvider.h' file not found， 而且xcode工程里的library的库都缺失

**Comment by Lxxyx** [comment]
http://reactnative.cn/docs/0.48/getting-started.html
http://reactnative.cn/post/4301

**Comment by Lxxyx** [comment]
RN iOS 0.45以上版本开始需要依赖一些第三方编译库，这些库在国内下载都非常困难。

建议全局翻墙后再build
