### ISSUE TITLE
登录过期时，首页数据无法加载

### ISSUE THREAD

**Issue by airingursb** [1ibrary/1ibrary-front-end#25]
1. 登录状态容易自动过期，且无提示
2. 此时app无法正常使用，首页数据无法加载，只能注销之后重新登录

**Comment by Lxxyx** [comment]
1. 后端给 App 的Token过期时间应该尽可能长一些
2. 我这儿会加上定时登录，3600s一次

**Comment by Lxxyx** [comment]
已解决，等待晚上合并。
