### ISSUE TITLE
师兄？师姐？你好！我能请教您一个问题吗？

### ISSUE THREAD

**Issue by SmallerCoder** [1ibrary/1ibrary-front-end#34]
我现在在做一个react native应用开发，我跟老师一样正确设置了启动屏图案，可是当我真机测试的时候发现启动屏消失之后就一直卡死在那里，无法进入应用的主页面，这个问题我头疼了好久，不知道是什么原因造成的！QAQ

**Comment by mieruko0713** [comment]
你好。
这个教学可以做一个参考，我是17年四月份看的，不知道它有没有更新。
可以先排除一下看是不是版本的问题，如果不是，看一下应用主页面有没有报错？
推荐使用一个叫做react native debugger的工具 或许能帮助你找到原因^_^
