### ISSUE TITLE
你好，可以分享一下课程吗？

### ISSUE THREAD

**Issue by alexkie007** [1ibrary/1ibrary-front-end#4]
你好 在慕课网上看到了你的评价，然后找到了你到github，请问可以分享一下 
React Native开发跨平台Github App这门课程吗？

**Comment by mieruko0713** [comment]
抱歉，已经分享给团队的小伙伴了，希望支持正版哈～

**Comment by alexkie007** [comment]
正版的太贵了  如果你需要其他的资源   交换也可以

**Comment by Lxxyx** [comment]
@alexkie007 支持正版，另外对着文档就行了 = =，RN很简单的

**Comment by alexkie007** [comment]
@Lxxyx   😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢
